### ISSUE TITLE
Worldpainter files for Earth Survival saves

### ISSUE THREAD

**Issue by Mentillz** [MattiBorchers/MinecraftEarthMap#10]
Hello, can you upload the worldpainter files for Survival Version #3 1:1000, 1:2000, and 1:4000 on Google Drive or OneDrive please? I want to play on the save with structures but I don't like urban, borders, or streets and I cannot turn that off without the worldpainter save to edit the layers.

**Comment by MattiBorchers** [comment]
Hey, the WorldPainter files for the versions: "FULL-SURVIVAL GAMEPLAY" and "NO STRUCTURES / CREATIVITY" are the same. The only difference is the way Minecraft populates the map afterwards. There is a small part on my website describing the problem:

> This was a lot harder to achive. When populating the map with structures turned on, Minecraft will place them anywhere in the map (depending on a seed). This will cause some strange placements of villages over water, pyramids in snowy areas, and so on.

> The solution I found was the mod "Open Terrain Generator" (short OTG, available for Forge & spigotmc). Sadly only available for 1.12 at the moment.

So when you want a custom map (e.g. no borders / urban) and structures, you need to export the map and use the same method I used. **Warning! level of difficulty: expert**. You should be experienced with Spigot and OpenTerrainGenerator, because it's prone to error.

**Comment by Mentillz** [comment]
Can I change the population as it is on the survival version and make it all generate when I load in for the first time because I plan on converting the file to Bedrock Edition.

**Comment by MattiBorchers** [comment]
To learn and understand the problem, you can try it yourself. But there are several problems:

When using "structures" (in Minecraft it is calles "MapFeatures"), Minecraft will place villages, dungeons, etc. in the world, when the chunk gets loaded for the first time. The position of the structures is calculated by the map seed (which normally also calculates the terrain and the biomes). On the Earth Map, the terrain and the biomes are pre-defined, so the location of the structurs will not match the location of the biomes.

Another problem, when you want to convert the Map to Bedrock, it needs to be fully populated, so you need to load every chunk at least once. To automate this process, I used the spigot plugin "WorldBorder".

You have 2 options:
1: Use the map without MapFeatures, populate them with spigot and WorldBorder and convert the map to bedrock
2: Use the map with OpenTerrainGenerator (it's hard to get all settings correct) and do the same as before.

**Comment by Mentillz** [comment]
Alright, I plan on running a small server with a small group of people and myself on the 1:4000 scale. For WorldBorder once I set the border do I need to use a command to load all of the chunks or does WorldBorder scan all of the chunks within the set border. Also, since the Earth map is a rectangle can I set the WorldBorder to be a rectangular size?

**Comment by MattiBorchers** [comment]
Hey, all the commands you need are the following:

`wb shape rectangular`
`wb world setcorners -5376 -2688‬ 5376 2688‬`
`wb wrap world on`
`wb world fill 100 0 true`
`wb fill confirm`

You can modify the value 100 at the fill command... higher means more chunks per second, but can cause lags. 10-100 is accaptable I think.

I would recommand spigot. Forge is mostly used for mods, where you also have to mod the clients. Spigot is for vanilla clients.

**Comment by Mentillz** [comment]
If I used WorldBorder on Forge then it will not populate the chunks once I put it through MCC Tool Chest and send it to Bedrock since its technically a "mod" and not part of the vanilla client? Thanks for the help, I appreciate it. Your map is amazing.

**Comment by Mentillz** [comment]
Alright. Void the last question. I'm on Spigot, I have the WorldBorder plugin. I'm so close all it says is "you don't have sufficient privileges to use that" when I type in /wb

Is there something I need to adjust in my Local Server files for the Spigot server?

**Comment by Mentillz** [comment]
[https://gyazo.com/db8c77e3f748c3f756b9f46e49fc9960](url)

For some reason the worldborder is working but I can't do the set border command (I have Spigot and everything else works fine)

**Comment by Mentillz** [comment]
Just leaving a little update. I got the world to work. I set the border using a workaround with /wb set <> <> and got it to work then I filled it to load all the chunks then ported it to Bedrock. Appreciate the support. Thanks!
