### ISSUE TITLE
Using linux, not working

### ISSUE THREAD

**Issue by JosephcatZ** [MattiBorchers/MinecraftEarthMap#11]
it says that globecover10k.png is not found

**Comment by MattiBorchers** [comment]
Hey. It sounds like the path to the files is wrong, because this specific image is the first one that is used in the script. Be sure to download all files from the GitHub project and change the variable "path" in the script.js file to match your local folder.

**Comment by 1271** [comment]
> and change the variable "path" in the script.js file to match your local folder

Perhaps it makes sense to use relative paths?

**Comment by MattiBorchers** [comment]
You can use relative or absolute paths in the script. The "path" variable is just a string and you can use the path relative to the script.js file. Works both ways.

**Comment by 1271** [comment]
I understand. I mean that this can be put in the repository. So people ask fewer questions.
Never mind
