### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by winnipeg21** [MattiBorchers/MinecraftEarthMap#12]
When loading the map in mc is all good, after rendering out in world painter in 1.13 then losd in 1.13 then load again in 1.14 all the trees are gone. I'm also trying to get deeper oceans and nature structures.

**Comment by MattiBorchers** [comment]
Related: [https://github.com/Captain-Chaos/WorldPainter/issues/129](https://github.com/Captain-Chaos/WorldPainter/issues/129) It's a problem with the new 1.14 map format (yes, it changed again)

**Comment by winnipeg21** [comment]
can you make the oceans deeper?

**Comment by MattiBorchers** [comment]
I have no plans to do it, but you can do it yourself by changing the heightmap (only the bathemetry) and run the script afterwards. All images and sources are linked in the project.
