### ISSUE TITLE
How can i generate a 1/100 map?

### ISSUE THREAD

**Issue by gundami** [MattiBorchers/MinecraftEarthMap#14]
i try to change the scale to 400,but it dosen't work

**Comment by MattiBorchers** [comment]
A 1/100 map would be a scaling of 1000. But I think the size is to large for WorldPainter to handle. So 1/1000 is the limit (with this method)

**Comment by 1271** [comment]
You can split the images and process them in 100 cycles (10x10)

**Comment by MattiBorchers** [comment]
You could split the images, but the resolution wont be higher. You would get rasters of 2x2 blocks ingame (for heightmap, biome, terrain, etc.)

**Comment by Mytherals** [comment]
Would there be any other method to create a scale of 1:500 or similar? And could you run this map through a modpack and generate it accordingly?

**Comment by MattiBorchers** [comment]
This map works with a lot of mods. Only mods that add new biomes don't work (right).
You can take a look at "Terrarium" to genreate a map from osm data and higher scales.
