### ISSUE TITLE
Provide more mirrors for download.

### ISSUE THREAD

**Issue by Charadon** [MattiBorchers/MinecraftEarthMap#16]
Apologies if this is the wrong place, as I couldn't find anywhere else to suggest this. For the past 3 days i've been trying to download the world, but google drive always says "This file has exceeded download limits" Would it be possible to provide a mediafire mirror or (even better) a torrent of the world downloads?

**Comment by MattiBorchers** [comment]
Mediafire also have a bandwidth limitation (of 1 TB, which equals 2 downloads per day of the 1:1000 survival map). Mega.nz has the same problem. But you can try this method to bypass the download limit of Google: https://www.geekrar.com/fix-bypass-google-drive-download-limit-error/

**Comment by Charadon** [comment]
Yeah, unforunately they all have bandwidth limits, which is why I suggested providing a torrent, which would bypass this entire issue, and take a load off of hosting the download centrally. If you want, I can make a torrent of it (When I get all the downloads atleast lol)
