### ISSUE TITLE
Question: What are your Export settings for WorldPainter

### ISSUE THREAD

**Issue by JosephMillsAtWork** [MattiBorchers/MinecraftEarthMap#19]
So As I am sure you are aware that Worldpainter now has 1.14.4 support(beta) I have alter your script   a tiny bit so that it is 40 on the scale and changed groundmaterial to biome. 

I am getting issues with trees not generating and also structures ect.   Was wondering if you could send me your export settings for world paint so that I can compare please and thanks :)

**Comment by MattiBorchers** [comment]
Take a look here: https://www.reddit.com/r/Worldpainter/comments/dkn4wh/worldpainter_274_some_small_improvements/

Quote: "In addition, since it unfortunately transpires that Minecraft 1.14 no longer supports populating the map after generation, the Populate and Structures options will be disabled for the Minecraft 1.14 format."

So it needs a complete overhaul of the script to get a playable map, because at the moment, the map requieres the population.

**Comment by JosephMillsAtWork** [comment]
@MattiBorchers  Yeah I noticed that after a couple of runs. I was however able to get the maps up and running with stuctures and a couple other custom bioms for 1.15 I was gonna write up a wiki here on it but I dont think that I have the permissions.  Note I also made a 1:500 scale one as well.

but as far as > 1.12 there is 100% some hacky things one must do.

**Comment by JosephMillsAtWork** [comment]
The next images that I post is prove that it is doable go ahead and load up your 1.12.2 with structures and go to the cords in the image :) note the version and what not in the debug screen

**Comment by JosephMillsAtWork** [comment]
End Portal that is odd of the coast of Florida USA 

![EndPortalFL](https://user-images.githubusercontent.com/8931995/70852609-4150ef80-1e58-11ea-8e38-a9f1ddd534e7.png)

I am willing to go to any cords you like and take a screenshot :1st_place_medal:

**Comment by MattiBorchers** [comment]
The "1.12.2 with structures" map is completly pre-generated. So you are able to play it in newer version, but this maps lacks of new blocks, like bamboo, honey, new villages etc.

**Comment by JosephMillsAtWork** [comment]
@MattiBorchers sorry for the delayed response (rl issues) when I used the 1.12 map and upgraded to 13>14 I got lots of chunk errors and things generated (like a ocean where New england USA located ) 

The trick was to downgrade worldpainter for 1.13 and not 1.14. then you can generate structures . One still needs to make woodland mansion images  and import in the script. 
But ,
New villages,bamboo,kelp , sea grass , coral and many other things generate.  And best of all there is no chunk errors.  Of course some of the IDs need to be moved around for bamboo jungle biomes ECT.

**Comment by MattiBorchers** [comment]
ok, what exactly did you do? (to replicate the outcome) you exported the map for 1.13 (with worldpainter 2.6.5, with populate the entire terrain and structures on). After that, you created a 1.15 server and opend the map with the -forceupdate argument? Now the map is generated with bamboo and beehives.

The villages (and other structures), are they in the right biomes or does Minecraft place them seemingly randomly? Normally he places structures using the level seed, which does not match the biomes on the custom map. Thats why I needed mods for 1.12.2, to get the structures right.

**Comment by JosephMillsAtWork** [comment]
Hey @MattiBorchers  Hope all is well. 
** be careful and make backups at each version bump. **

So I had to do the following. 

1)  Download and install Minecraft 1.12 (if you want biome stuff when editing)
2)  Download and install World Painter 2.6.5 
3)  Use git to get this repo
    * Download height map and others that are on a gdrive
    * Alter the colors of some of the images say biomes and OceanBiomeMap and keep track of the color. I did this in gimp. 
    * Alter ColorToBiomeMappings
    * Alter the javascript file and add the new colors.This is why it is important that 1.12.2 is installed. If it is not the worldpainter yells at you in the stdout found that out the hard way lol

4 ) Use the wpscript to run against the javascript file to get the .world file. Make sure that you bump up the memory to a massive amount.  I altered the wpscript and also the worldpainter scripts and hardcoded 

````shell
-Xmx28G -Di4j.vpt=true
```` 
instead of the 
````shell
$INSTALL4J_ADD_VM_PARAMS
````
and changed the path for my java to match up with oracles jre which I installed to 

````
/usr/local/java/jre1.8.0_231/bin/java
````

My example would be 

````shell
#echo JOSEPH $INSTALL4J_ADD_VM_PARAMS
#exit 0 

return_code=0
$INSTALL4J_JAVA_PREFIX exec "/usr/local/java/jre1.8.0_231/bin/java" -client -Dinstall4j.jvmDir="/usr/local/java/jre1.8.0_231/" -Dexe4j.moduleName="$prg_dir/$progname" "-Dinstall4j.launcherId=554" "-Dinstall4j.swt=false" "$vmov_1" "$vmov_2" "$vmov_3" "$vmov_4" "$vmov_5" -Xmx28G -Di4j.vpt=true -classpath "$local_classpath" com.install4j.runtime.launcher.UnixLauncher launch 829cb152 0 0 org.pepsoft.worldpainter.tools.ScriptingTool  "$@"
return_code=$?
````

5)  Open up the world file in worldpainter gui again alter the shell script. then alter map to your liking, remove auto save timer and other misc settings. Make sure that you look at the full map . zoom out and scan it. 

6) I altered some of the script before hand and also some of the images for biomes I liked what was there but felt like the midwest of the us and other places should be plains ect.I also used a custom brush to make a spawn point in the middle and set it as well. None of this should matter. But what does matter is that you add a custom biome with the correct ID to match up to the jungle with bamboo. Then alter the images to add a custom color (168,169 ect)

https://minecraft.gamepedia.com/Biome/ID

7)  Export 
    a. World type Default
    b. structures checked
    c. Map format beta 1.13.2 or later
    d. export everything checked
    e. Mode survival
    f. Click "Other Layers" and make sure that you check "Allow Minecraft to populate the entire terrain"
    g. I altered some of the custom layers (endportal (n,w,e,s ) streets and cities ) This was because I wanted concert and endrods ect

8) Download and open up minecraft 1.13.2 just to make sure that all is good.  Do not open the map yet. 

9) Use your favorite NBT editor to alter level.dat & make sure that spawn is right and that Mapfeatures is set to 1 change the generator name to default_1_1, Make sure that initialized is not there if it is even if 0 delete it. set genVersion to 0 

10) open minecraft 1.13.2 and load your level This will take some time. Don't play the game just load it up. 

11) quit the game and go back to the launcher and download (if you don't have it )  1.14.4 I used my optifine installed version. DO not launch your game just launch minecraft client to make sure it works.  Bump ram if need be. 

12) again in the nbt editor repeat step 9 gen version should be 1 now

13) load map in minecraft

14 ) do 12 again but with 1.15 

As far as your questions about the villages. Yes they are the new villages but some of them are in the ocean :-1:  The mansions did not generate in say Russia and what not like the old ones did on your 1.12 version.  I tried using and altering your nbt files for this but sadly this did nothing.

I hope that this answers your question.   If not I am glad to talk more,

**Comment by JosephMillsAtWork** [comment]
also make sure that you alter your js script to 

````javascript
var version = "1-13"
var scale = 40;
var groundmaterial = "biomes";

````


also things like 

````
var jBamboo = wp.getTerrain().fromFile(path+'terrain/jBamboo.terrain').go();
````


ect But that last one is only needed if you really want to have the bamboo jungle later on in the 2nd upgrade to 1.14.4

**Comment by JosephMillsAtWork** [comment]
@MattiBorchers  hope your holidays are going well.  I consider this issue to be closed as stated above I was able to get things generated.  Let me know if you would like a merge request or anything.
