### ISSUE TITLE
Un-cropped biome png, other pngs, to load terrain/other scales, out to 180/90 degrees fully.

### ISSUE THREAD

**Issue by Delvin4519** [MattiBorchers/MinecraftEarthMap#22]
The provided pngs are cropped to 179.2/89.6 degrees meaning that it is not currently possible to generate other sizes from the existing 3 due to the ratio change. Currently, the 1:4000 map which is 10752x5376 is more than 500mb and some want a smaller scale, and there are whole earth maps larger than 43008x21504 and still a reasonable size.

By providing the original pngs at 43200x21600 then, my thinking, make copies so there would be a 46080x23040 png file (46080 is a multiple of 512 and 360, no cropping necessary, 180W/E 90 N/S aligned to the chunk boundary) for the 1:1000 that can easily be downscaled, 2x, 4x, 8x, down to 5760x2880 for a 1:8000 scale. This also allows for easy comparison of detail of the earth map versus earth tiles by having the 1:1000 earth map be exactly 1:4 the scale of the smallest earth tiles

I am not sure what the maximum limit of worldpainter is but I suspect it has to do with handling images larger than 65536 pixels or an area greater than 2.147 billion pixels squared. So I also think it might be possible to provide a whole earth map at a scale of 1:612 OR 1:619, which is slightly under the integer limits, which hopefully worldpainter might be able to handle. (note the image will need to be cropped slightly for this 1:61x one, details in the attachment below). Generating a 1:61x earth map probably will need 40-48GB of RAM though, and use ~44GB of space.

![image](https://user-images.githubusercontent.com/23464599/75059877-d7824100-54ab-11ea-9191-a62c4adbfcb1.png)

**Comment by MattiBorchers** [comment]
All uncropped source images are linked in the README.md.
