### ISSUE TITLE
Repo and website lack OpenStreetMap attribution.

### ISSUE THREAD

**Issue by MoiraPrime** [MattiBorchers/MinecraftEarthMap#27]
I just wanted to bring to your attention that this repo and the website both contain content derived from OpenStreetMap data. As an OpenStreetMap contributor myself, it's great to see our data used in all kinds of cool projects. We provide the maintenance of this high quality dataset free of charge, and one of the only major things we ask for in return is that you attribute us.

To attribute to OSM, please include a ©️OpenStreetMap Contributors attribution, with a link to https://openstreetmap.org/copyright. You can also find out more about the license used for OSM at that link.

**Comment by DerMattinger** [comment]
Thanks for the info, I added the link in the repo readme and on the website at the specific places where I refer to OSM data.
