### ISSUE TITLE
Info on how to generate image files

### ISSUE THREAD

**Issue by dextonanderson** [MattiBorchers/MinecraftEarthMap#5]
Hi! I really like the project and how well it works for how simple it is.

I was wondering if you could provide some info on how you select the right sized image files from NASA etc... Maybe in the README?

Specifically, I was wanting to generate a 1:500 scale map (yes, I do have a ton of ram/HDD space/etc).

**Comment by MattiBorchers** [comment]
Hi, I already tried to create a 1:500 map myself. However, the limitation is not exclusively with the amount of memory. Another problem is the imigabuffer of java, which already reaches its limits with the 1:1000 images. Thats why I had to split the globcover images. Of course, you can do this to all images, but it is a lot more affort. (Maybe it is possible to generate 4 seperate worlds and put the region files together at the end.)

Regarding the images, I will add a small description of how I chose the right scaling.

**Comment by dextonanderson** [comment]
Ohh I see that's why the globcover images were split... Thats really interesting.

I appreciate the insight though. If I do get a 1:500 generated, I'll comment here for anyone else who may be interested.

(Feel free to close this issue)

**Comment by BiGUNMAN** [comment]
@dextonanderson Did you end up getting 1:500 generated?

**Comment by dextonanderson** [comment]
@BiGUNMAN I did not, sorry
