### ISSUE TITLE
Some questions about 1.14

### ISSUE THREAD

**Issue by ShCby** [MattiBorchers/MinecraftEarthMap#8]
Hello, I recently tried to use your script to generate a 1.14 World, but I found that there are no architectural and biome features. Can you share your .world file, or do you have any good suggestions?

**Comment by MattiBorchers** [comment]
Hey, worldpainter does not support the new map format of 1.14 at the moment. The only way to play this map is to load and populate it with 1.13 and then copy the map to 1.14 (you will still have missing features, like bamboo)
