### ISSUE TITLE
Issue populating world with OTG

### ISSUE THREAD

**Issue by Dyllan2000alfa** [MattiBorchers/MinecraftEarthMap#9]
I'm trying to populate the 1:1000 scale for a modded survival server. How did you configure OTG cause every time I try and play the maps with OTG loaded with biome mode set to FromImage no forest are loaded, Everything else works fine. I have checked biomes and it looks like all biomes are correct.

**Comment by Dyllan2000alfa** [comment]
So I figured out that my issue was biome colors not matching. I spent the better part of a day looking at world painter and the OTG image provided trying to match all colors. Now i'm getting a "Exception preparing structure feature" error when I try to open the world. I looked at the log and the error is occurring when OTG is attempting to place a mine shaft.  Would it be possible for you to add your OTG world folder to the repository so that me and anyone else trying trying to populate a custom survival world wont have any issues.

**Comment by MattiBorchers** [comment]
Hey, what version of Minecraft and OTG do you use? Forge or spigot. Sounds more like an OTG bug. Have you installed any other mods/plugins? I can upload my OTG folder and do a little tutorial, but it will take some time.

**Comment by Dyllan2000alfa** [comment]
I'm running the latest version of OTG for 1.12 with forge 14.23.5.2836. I was getting this error in a test profile I created with no other mods. I will eventually be using the enigmatica 2 expert mod pack. I have gotten OTG working when creating other worlds. It was when i set all the biome colors that OTG started to give me that error. If you could upload your OTG folder that would be great cause I think my problem may be messed up biome colors since thats when the error started to occur.

**Comment by MattiBorchers** [comment]
Hello, I'm sorry the answer took a little longer. I have problems with Forge and OTG myself, but I can recommend "Painted Biomes". It's like the "fromImage" function of OTG as a stand-alone mod. I will upload the config file to GitHub. Just put the image (BiomeMap--k.png) in the folder "config\paintedbiomes\templates\dim0\" and rename the image to "biomes.png" and replace the "paintedbiomes.cfg" file with the one I provided.

**Comment by Dyllan2000alfa** [comment]
Thanks, Checked it this past weekend and everything works.
